# Generated by Django 6.0 on 2026-01-25 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('post_image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
