# Generated by Django 6.0 on 2026-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_of_author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
